spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/device_management
    username: postgres
    password: chedly
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false

  sql:
    init:
      mode: never