server:
    port: 9005
spring:
    cloud:
        config:
            enabled: false
    application:
        name: device-service
    datasource:
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://localhost:5432/device_management
        username: postgres
        password: chedly
    jpa:
        hibernate:
            ddl-auto: update
        database: postgresql
        database-platform: org.hibernate.dialect.PostgreSQLDialect
    kafka:
        bootstrap-servers: localhost:9092
        producer:
            key-serializer: org.apache.kafka.common.serialization.StringSerializer
            value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
            properties:
                spring.json.add.type.info: false
                spring.json.type.mapping: >
                    deviceCreated:com.realtime_monitoring.device_management.kafka.event.DeviceCreatedEvent,
                    deviceUpdated:com.realtime_monitoring.device_management.kafka.event.DeviceUpdatedEvent,
                    deviceDeleted:com.realtime_monitoring.device_management.kafka.event.DeviceDeletedEvent
        # kafka:
    #     bootstrap-servers: localhost:9092
    #     producer:
    #         key-serializer: org.apache.kafka.common.serialization.StringSerializer
    #         value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

mqtt:
    broker: ssl://192.168.1.122:8883
    client-id: monitoring-backend
    topic: tenants/+/devices/+/metrics
    qos: 1
    ca-cert: C:/mqtt/backend/ca.crt
    client-cert: C:/mqtt/backend/backend.crt
    client-key: C:/mqtt/backend/backend.key
pki:
  ca-cert: C:/mqtt/backend/ca/ca.crt
  ca-key: C:/mqtt/backend/ca/ca.key
#   ca-cert: C:\mqtt\backend\ca.crt
#   client-cert: C:\mqtt\backend\backend.crt
#   client-key: C:\mqtt\backend\backend.key
